"""
shared/models.py — Data models using Python dataclasses.

These lightweight dataclasses serve as the canonical data transfer objects
(DTOs) between the scanner_agent, backend_api, and database layers.
They are intentionally free of ORM or framework dependencies.

OWASP ASVS V1.5: Data classification — models carry no secrets.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

# ─── Utility ─────────────────────────────────────────────────────────────────


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


# ─── Device Model ─────────────────────────────────────────────────────────────


@dataclass
class Device:
    """Represents a discovered network device."""

    mac_address: str
    last_known_ip: str
    hostname: str = "Unknown"
    friendly_name: Optional[str] = None
    vendor: str = "Unknown"
    device_type: str = "unknown"
    operating_system: str = "Unknown"
    confidence_score: int = 0
    is_online: bool = True
    risk_score: int = 0
    is_whitelisted: bool = False
    is_blacklisted: bool = False
    notes: str = ""
    open_ports: str = ""  # Comma-separated port list
    mitre_tags: str = ""  # Comma-separated MITRE T-codes
    first_seen: str = field(default_factory=_now_iso)
    last_seen: str = field(default_factory=_now_iso)
    deleted_at: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        # Parse open_ports to list for API consumers
        d["open_ports_list"] = [int(p) for p in self.open_ports.split(",") if p.strip().isdigit()]
        d["mitre_tags_list"] = [t.strip() for t in self.mitre_tags.split(",") if t.strip()]
        return d

    @classmethod
    def from_row(cls, row: dict) -> "Device":
        """Construct from a database row dict."""
        return cls(
            mac_address=row.get("mac_address", ""),
            last_known_ip=row.get("last_known_ip", ""),
            hostname=row.get("hostname", "Unknown"),
            friendly_name=row.get("friendly_name"),
            vendor=row.get("vendor", "Unknown"),
            device_type=row.get("device_type", "unknown"),
            operating_system=row.get("operating_system", "Unknown"),
            confidence_score=row.get("confidence_score", 0),
            is_online=bool(row.get("is_online", 1)),
            risk_score=row.get("risk_score", 0),
            is_whitelisted=bool(row.get("is_whitelisted", 0)),
            is_blacklisted=bool(row.get("is_blacklisted", 0)),
            notes=row.get("notes", ""),
            open_ports=row.get("open_ports", ""),
            mitre_tags=row.get("mitre_tags", ""),
            first_seen=row.get("first_seen", _now_iso()),
            last_seen=row.get("last_seen", _now_iso()),
            deleted_at=row.get("deleted_at"),
        )


# ─── Alert Model ──────────────────────────────────────────────────────────────


@dataclass
class Alert:
    """Represents a security alert generated by threat detection."""

    alert_type: str
    description: str
    severity: str  # LOW | MEDIUM | HIGH | CRITICAL
    confidence: int = 50  # 0-100
    evidence: str = ""  # JSON-encoded evidence blob
    affected_mac: Optional[str] = None
    mitre_attack: str = ""  # e.g. "T1557.002"
    cwe_id: str = ""  # e.g. "CWE-300"
    recommended_action: str = ""
    cvss_score: Optional[float] = None
    timestamp: str = field(default_factory=_now_iso)
    is_resolved: bool = False
    id: Optional[int] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_row(cls, row: dict) -> "Alert":
        return cls(
            id=row.get("id"),
            alert_type=row.get("alert_type", ""),
            description=row.get("description", ""),
            severity=row.get("severity", "LOW"),
            confidence=row.get("confidence", 50),
            evidence=row.get("evidence", ""),
            affected_mac=row.get("affected_mac"),
            mitre_attack=row.get("mitre_attack", ""),
            cwe_id=row.get("cwe_id", ""),
            recommended_action=row.get("recommended_action", ""),
            cvss_score=row.get("cvss_score"),
            timestamp=row.get("timestamp", _now_iso()),
            is_resolved=bool(row.get("is_resolved", 0)),
        )


# ─── Threat Event (internal) ─────────────────────────────────────────────────


@dataclass
class ThreatEvent:
    """
    Intermediate object produced by the threat detector before persistence.
    Carries all evidence needed to create an Alert record.
    """

    alert_type: str
    description: str
    severity: str
    confidence: int
    evidence: Dict[str, Any] = field(default_factory=dict)
    affected_mac: Optional[str] = None
    affected_ip: Optional[str] = None
    mitre_attack: str = ""
    cwe_id: str = ""
    recommended_action: str = ""
    cvss_score: Optional[float] = None
    timestamp: str = field(default_factory=_now_iso)

    def to_alert(self) -> Alert:
        import json

        return Alert(
            alert_type=self.alert_type,
            description=self.description,
            severity=self.severity,
            confidence=self.confidence,
            evidence=json.dumps(self.evidence, default=str),
            affected_mac=self.affected_mac,
            mitre_attack=self.mitre_attack,
            cwe_id=self.cwe_id,
            recommended_action=self.recommended_action,
            cvss_score=self.cvss_score,
            timestamp=self.timestamp,
        )


# ─── Packet Payload ───────────────────────────────────────────────────────────


@dataclass
class PacketPayload:
    """
    Structured representation of a captured network packet.
    Produced by the sniffer and consumed by the evaluator.
    """

    timestamp: str
    src_mac: str
    dst_mac: str
    src_ip: Optional[str] = None
    dst_ip: Optional[str] = None
    src_port: int = 0
    dst_port: int = 0
    protocol: str = "Unknown"
    dns_query: Optional[str] = None
    hostname: Optional[str] = None
    ttl: Optional[int] = None
    dhcp_options: Optional[Dict] = None
    mdns_info: Optional[str] = None
    ssdp_info: Optional[str] = None

    @classmethod
    def from_dict(cls, d: dict) -> "PacketPayload":
        return cls(
            timestamp=d.get("timestamp", _now_iso()),
            src_mac=d.get("src_mac", "00:00:00:00:00:00"),
            dst_mac=d.get("dst_mac", "00:00:00:00:00:00"),
            src_ip=d.get("src_ip"),
            dst_ip=d.get("dst_ip"),
            src_port=d.get("src_port", 0),
            dst_port=d.get("dst_port", 0),
            protocol=d.get("protocol", "Unknown"),
            dns_query=d.get("dns_query"),
            hostname=d.get("hostname"),
            ttl=d.get("ttl"),
            dhcp_options=d.get("dhcp_options"),
            mdns_info=d.get("mdns_info"),
            ssdp_info=d.get("ssdp_info"),
        )

    def to_dict(self) -> dict:
        return asdict(self)


# ─── Fingerprint Result ───────────────────────────────────────────────────────


@dataclass
class FingerprintResult:
    """Result of device fingerprinting."""

    device_type: str = "unknown"
    operating_system: str = "Unknown"
    confidence: int = 0
    vendor: str = "Unknown"
    evidence_sources: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# ─── Network Status ───────────────────────────────────────────────────────────


@dataclass
class NetworkStatus:
    """Current network connectivity state."""

    ssid: str = ""
    local_ip: str = ""
    gateway: str = ""
    subnet: str = ""
    connected: bool = False
    interface: str = ""
    subnet_mismatch: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# ─── Health Status ────────────────────────────────────────────────────────────


@dataclass
class ComponentHealth:
    """Health status of a single system component."""

    name: str
    status: str  # "ok" | "warn" | "error"
    detail: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
